### ISSUE TITLE
isRegistered

### ISSUE THREAD

**Issue by jonschlinkert** [tunnckoCore/base-plugins-enhanced#2]
[here](https://github.com/tunnckoCore/base-plugins-enhanced/blob/master/index.js#L42) you will need to ensure that `app` has an `isRegistered` function first. 

edit: this is why I use `is-valid-app`

**Comment by tunnckoCore** [comment]
hm. I'll try.

**Comment by tunnckoCore** [comment]
seems it worked for this plugin, huh. :D

**Comment by tunnckoCore** [comment]
Hm yea... missed the `!`, so when it is `if (!utils.isValid(app, 'base-plugins-enhanced')) return` everything fails. As before few weeks with the `base-extract-comments`.

@jonschlinkert I don't know what's up.

**Comment by jonschlinkert** [comment]
it's because the app needs to have `app.isApp = true`.

I haven't even looked at the code but I'm sure that's what it is. You need that unless you want your plugin to be loaded onto every object. Keep in mind that if someone else uses your plugin, and they do something like the following (which is essentially what generators do, so that plugins will be loaded onto sub-generators):

``` js
app.use(function plugin() {
  this.use(enhanced());
  return plugin;
});
```

Your plugin will be loaded onto everything, even if it's not an "app". So it would be loaded onto view collections and individual views.

**Comment by tunnckoCore** [comment]
> it's because the app needs to have

Hm, okey. I've seen that in couple of times that you do it.
